CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(50) NOT NULL,
	WRITER VARCHAR(20) NOT NULL, -- MEMBER의 MID : 외래키는 상대 테이블의 PK 사용함
	BREAD INT DEFAULT 0,
	BLIKE INT DEFAULT 0,	
	BDATE VARCHAR(25) NOT NULL
);

CREATE TABLE BOARDL(
	BID INT NOT NULL,
	MID VARCHAR(20) NOT NULL,
	CHECKL INT NOT NULL -- 0일때 좋아요+1 / 1일때 좋아요-1
);
SELECT * FROM BOARDL;
DROP TABLE BOARDL;
(SELECT * FROM BOARD WHERE TITLE LIKE '%ww%');
SELECT B.*, M.MNAME FROM BOARD B, MEMBER M WHERE B.WRITER = M.MID ORDER BY B.BID DESC;
SELECT B.*, M.MNAME FROM BOARD B, MEMBER M WHERE B.WRITER = M.MID(+) ORDER BY B.BID DESC;
SELECT SYSDATE FROM DUAL;
UPDATE BOARDL SET CHECKL=0 WHERE BID=10 AND MID=1;
SELECT B.*, M.MNAME FROM (SELECT * FROM BOARD WHERE WRITER LIKE '%asdasd%') B, MEMBER M WHERE B.WRITER = M.MID(+) ORDER BY B.BID DESC;
-- 추가해볼만한 칼럼
-- 1. 작성일 : 날짜 타입
-- 2. 좋아요 수 : 테이블 관계, 이퀄조인, 외래키
-- 3. 조회수 : scope 이슈 / 로직